/**
 * Generated by orval v8.0.0-rc.5 🍺
 * Do not edit manually.
 * Orders APIs
 * RESTful APIs for managing customers, vendors, carts, payments, and orders operations in the Ordering Application.
These endpoints allow customers to browse products, manage shopping carts, place orders, and process payments.
Includes secure authentication and authorization mechanisms using JWT tokens.

 * OpenAPI spec version: v1.0.0
 */
/**
 * User create request
 */
export interface UserCreateRequest {
  username: string;
  email: string;
  password: string;
  role: string;
  enabled?: boolean;
  credentialsNonExpired?: boolean;
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
}

export type AddressAddressType = (typeof AddressAddressType)[keyof typeof AddressAddressType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AddressAddressType = {
  BILLING: "BILLING",
  RESIDENTIAL: "RESIDENTIAL",
  POSTAL: "POSTAL",
  OFFICE: "OFFICE",
  SHIPPING: "SHIPPING",
} as const;

export interface AuditMetaData {
  createdBy?: string;
  createdDate?: string;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
}

export interface Address {
  id?: number;
  addressType?: AddressAddressType;
  /**
   * @minLength 5
   * @maxLength 2147483647
   */
  street: string;
  /**
   * @minLength 2
   * @maxLength 2147483647
   */
  city: string;
  /**
   * @minLength 2
   * @maxLength 2147483647
   */
  state: string;
  /**
   * @minLength 2
   * @maxLength 2147483647
   */
  country: string;
  /**
   * @minLength 4
   * @maxLength 2147483647
   */
  pinCode: string;
  version?: number;
  auditMetaData?: AuditMetaData;
}

export interface Category {
  id?: number;
  /**
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  version?: number;
}

export interface Image {
  id?: number;
  fileName?: string;
  contentType?: string;
  downloadUrl?: string;
  version?: number;
  auditMetaData?: AuditMetaData;
}

export interface Product {
  id?: number;
  /**
   * @minLength 3
   * @maxLength 255
   */
  name: string;
  /**
   * @minLength 10
   * @maxLength 600
   */
  description: string;
  price?: number;
  discountedPrice?: number;
  stock?: number;
  category: Category;
  images?: Image[];
  version?: number;
  auditMetaData?: AuditMetaData;
}

export type RoleRole = (typeof RoleRole)[keyof typeof RoleRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoleRole = {
  ROLE_CUSTOMER: "ROLE_CUSTOMER",
  ROLE_USER: "ROLE_USER",
  ROLE_SELLER: "ROLE_SELLER",
  ROLE_ADMIN: "ROLE_ADMIN",
  ROLE_MODERATOR: "ROLE_MODERATOR",
} as const;

export interface Role {
  id?: number;
  role?: RoleRole;
}

export interface User {
  id?: number;
  /**
   * @minLength 1
   * @maxLength 100
   */
  username: string;
  /**
   * @minLength 2
   * @maxLength 100
   */
  password: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  email: string;
  enabled?: boolean;
  roles?: Role[];
  credentialsNonExpired?: boolean;
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
}

export interface Seller {
  id?: number;
  firstName?: string;
  lastName?: string;
  phone?: string;
  addresses?: Address[];
  user?: User;
  version?: number;
  auditMetaData?: AuditMetaData;
  products?: Product[];
}

export interface CartItem {
  id?: number;
  product?: Product;
  quantity?: number;
  price?: number;
  discount?: number;
  auditMetaData?: AuditMetaData;
  discountedPrice?: number;
}

export interface Cart {
  id?: number;
  cartItems?: CartItem[];
  totalPrice?: number;
  auditMetaData?: AuditMetaData;
}

export interface PaymentDetails {
  cardHolderName?: string;
  cardType?: string;
  cardNumber?: string;
  expiryDate?: string;
  cvv?: string;
}

export type PaymentPaymentType = (typeof PaymentPaymentType)[keyof typeof PaymentPaymentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentPaymentType = {
  CREDIT_CARD: "CREDIT_CARD",
  CASH: "CASH",
  PAYPAL: "PAYPAL",
  BANK_TRANSFER: "BANK_TRANSFER",
} as const;

export type PaymentPaymentStatus = (typeof PaymentPaymentStatus)[keyof typeof PaymentPaymentStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentPaymentStatus = {
  PENDING: "PENDING",
  CREATED: "CREATED",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
} as const;

export interface Payment {
  id?: number;
  paymentIdentifier?: string;
  paymentType?: PaymentPaymentType;
  paymentStatus?: PaymentPaymentStatus;
  paymentDetails?: PaymentDetails;
  amount?: number;
  paymentGatewayName?: string;
  paymentGatewayStatus?: string;
  paymentGatewayMessage?: string;
  paymentGatewayErrorDescription?: string;
  version?: number;
}

export interface OrderItem {
  id?: number;
  product?: Product;
  quantity?: number;
  orderItemTotalPrice?: number;
  version?: number;
  auditMetaData?: AuditMetaData;
}

export type OrderOrderStatus = (typeof OrderOrderStatus)[keyof typeof OrderOrderStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderOrderStatus = {
  NEW: "NEW",
  PENDING: "PENDING",
  SHIPPED: "SHIPPED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
} as const;

export interface Order {
  id?: number;
  orderId?: string;
  orderStatus?: OrderOrderStatus;
  payment?: Payment;
  orderItems?: OrderItem[];
  totalPrice?: number;
  shippingPrice?: number;
  version?: number;
}

export interface Customer {
  id?: number;
  firstName?: string;
  lastName?: string;
  phone?: string;
  addresses?: Address[];
  user?: User;
  version?: number;
  auditMetaData?: AuditMetaData;
  cart?: Cart;
  orders?: Order[];
}

/**
 * Wrapper for Username, Password
 */
export interface LoginRequest {
  username: string;
  password: string;
}

export interface LoginResponse {
  jwt?: string;
  username?: string;
  roles?: string[];
}

export interface SortObject {
  empty?: boolean;
  sorted?: boolean;
  unsorted?: boolean;
}

export interface PageableObject {
  offset?: number;
  sort?: SortObject;
  paged?: boolean;
  pageSize?: number;
  pageNumber?: number;
  unpaged?: boolean;
}

export interface PageProduct {
  totalPages?: number;
  totalElements?: number;
  size?: number;
  content?: Product[];
  number?: number;
  sort?: SortObject;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  pageable?: PageableObject;
  empty?: boolean;
}

export type OrderHistoryOrderStatus = (typeof OrderHistoryOrderStatus)[keyof typeof OrderHistoryOrderStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderHistoryOrderStatus = {
  NEW: "NEW",
  PENDING: "PENDING",
  SHIPPED: "SHIPPED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
} as const;

export interface OrderHistory {
  id?: number;
  orderId?: string;
  orderStatus?: OrderHistoryOrderStatus;
  customerId?: number;
  paymentId?: number;
  totalPrice?: number;
  shippingPrice?: number;
}

export interface PageCategory {
  totalPages?: number;
  totalElements?: number;
  size?: number;
  content?: Category[];
  number?: number;
  sort?: SortObject;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  pageable?: PageableObject;
  empty?: boolean;
}

export type UpdateImageBody = {
  files: Blob;
};

export type PatchCartParams = {
  productId: number;
  /**
   * @exclusiveMinimum 0
   */
  quantity: number;
};

export type AddProductToCartParams = {
  productId: number;
  /**
   * @exclusiveMinimum 0
   */
  quantity: number;
};

export type SaveProductBody = {
  product: Product;
  images?: Blob[];
};

export type CreateOrderParams = {
  paymentIdentifier: string;
};

export type AddImagesToAProductParams = {
  replaceAll?: boolean;
};

export type AddImagesToAProductBody = {
  files: Blob[];
};

export type SaveImagesBody = {
  files: Blob[];
};

export type SaveImageBody = {
  files: Blob;
};

export type ChangePasswordParams = {
  /**
   * @minLength 8
   * @maxLength 100
   */
  password: string;
};

export type GetProductsByPageParams = {
  name: string;
  page: number;
  size: number;
  sortDirection: string;
};

export type GetCategoriesByPageParams = {
  name: string;
  page: number;
  size: number;
  sortDirection: string;
};

export type DeleteCartParams = {
  productId: number;
};
