/**
 * Generated by orval v8.0.0-rc.5 🍺
 * Do not edit manually.
 * Orders APIs
 * RESTful APIs for managing customers, vendors, carts, payments, and orders operations in the Ordering Application.
These endpoints allow customers to browse products, manage shopping carts, place orders, and process payments.
Includes secure authentication and authorization mechanisms using JWT tokens.

 * OpenAPI spec version: v1.0.0
 */
import * as zod from "zod";

/**
 * @summary Update a user (PUT operation)
 */
export const UpdateUserBody = zod
  .object({
    username: zod.string(),
    email: zod.string(),
    password: zod.string(),
    role: zod.string(),
    enabled: zod.boolean().optional(),
    accountNonExpired: zod.boolean().optional(),
    credentialsNonExpired: zod.boolean().optional(),
    accountNonLocked: zod.boolean().optional(),
  })
  .describe("User create request");

/**
 * Create a new user with the given credentials
 * @summary Create a new user
 */
export const CreateUserBody = zod
  .object({
    username: zod.string(),
    email: zod.string(),
    password: zod.string(),
    role: zod.string(),
    enabled: zod.boolean().optional(),
    accountNonExpired: zod.boolean().optional(),
    credentialsNonExpired: zod.boolean().optional(),
    accountNonLocked: zod.boolean().optional(),
  })
  .describe("User create request");

export const GetSellerByIdParams = zod.object({
  id: zod.number(),
});

export const PutSellerParams = zod.object({
  id: zod.number(),
});

export const putSellerBodyAddressesItemStreetMin = 5;
export const putSellerBodyAddressesItemStreetMax = 2147483647;

export const putSellerBodyAddressesItemCityMin = 2;
export const putSellerBodyAddressesItemCityMax = 2147483647;

export const putSellerBodyAddressesItemStateMin = 2;
export const putSellerBodyAddressesItemStateMax = 2147483647;

export const putSellerBodyAddressesItemCountryMin = 2;
export const putSellerBodyAddressesItemCountryMax = 2147483647;

export const putSellerBodyAddressesItemPinCodeMin = 4;
export const putSellerBodyAddressesItemPinCodeMax = 2147483647;

export const putSellerBodyUserUsernameMax = 100;

export const putSellerBodyUserPasswordMin = 2;
export const putSellerBodyUserPasswordMax = 100;

export const putSellerBodyUserEmailMin = 0;
export const putSellerBodyUserEmailMax = 100;

export const putSellerBodyProductsItemNameMin = 3;
export const putSellerBodyProductsItemNameMax = 500;

export const putSellerBodyProductsItemDescriptionMin = 10;
export const putSellerBodyProductsItemDescriptionMax = 600;

export const putSellerBodyProductsItemCategoryNameMin = 2;
export const putSellerBodyProductsItemCategoryNameMax = 100;

export const PutSellerBody = zod.object({
  id: zod.number().optional(),
  firstName: zod.string().optional(),
  lastName: zod.string().optional(),
  phone: zod.string().optional(),
  addresses: zod
    .array(
      zod.object({
        id: zod.number().optional(),
        addressType: zod.enum(["BILLING", "RESIDENTIAL", "POSTAL", "OFFICE", "SHIPPING"]).optional(),
        street: zod.string().min(putSellerBodyAddressesItemStreetMin).max(putSellerBodyAddressesItemStreetMax),
        city: zod.string().min(putSellerBodyAddressesItemCityMin).max(putSellerBodyAddressesItemCityMax),
        state: zod.string().min(putSellerBodyAddressesItemStateMin).max(putSellerBodyAddressesItemStateMax),
        country: zod.string().min(putSellerBodyAddressesItemCountryMin).max(putSellerBodyAddressesItemCountryMax),
        pinCode: zod.string().min(putSellerBodyAddressesItemPinCodeMin).max(putSellerBodyAddressesItemPinCodeMax),
        version: zod.number().optional(),
        auditMetaData: zod
          .object({
            createdBy: zod.string().optional(),
            createdDate: zod.iso.datetime({}).optional(),
            lastModifiedBy: zod.string().optional(),
            lastModifiedDate: zod.iso.datetime({}).optional(),
          })
          .optional(),
      }),
    )
    .optional(),
  user: zod
    .object({
      id: zod.number().optional(),
      username: zod.string().min(1).max(putSellerBodyUserUsernameMax),
      password: zod.string().min(putSellerBodyUserPasswordMin).max(putSellerBodyUserPasswordMax),
      email: zod.email().min(putSellerBodyUserEmailMin).max(putSellerBodyUserEmailMax),
      enabled: zod.boolean().optional(),
      roles: zod
        .array(
          zod.object({
            id: zod.number().optional(),
            role: zod.enum(["ROLE_CUSTOMER", "ROLE_USER", "ROLE_SELLER", "ROLE_ADMIN", "ROLE_MODERATOR"]).optional(),
          }),
        )
        .optional(),
      accountNonExpired: zod.boolean().optional(),
      credentialsNonExpired: zod.boolean().optional(),
      accountNonLocked: zod.boolean().optional(),
    })
    .optional(),
  version: zod.number().optional(),
  auditMetaData: zod
    .object({
      createdBy: zod.string().optional(),
      createdDate: zod.iso.datetime({}).optional(),
      lastModifiedBy: zod.string().optional(),
      lastModifiedDate: zod.iso.datetime({}).optional(),
    })
    .optional(),
  products: zod
    .array(
      zod.object({
        id: zod.number().optional(),
        name: zod.string().min(putSellerBodyProductsItemNameMin).max(putSellerBodyProductsItemNameMax),
        description: zod
          .string()
          .min(putSellerBodyProductsItemDescriptionMin)
          .max(putSellerBodyProductsItemDescriptionMax),
        price: zod.number().optional(),
        discountedPrice: zod.number().optional(),
        stock: zod.number().optional(),
        category: zod.object({
          id: zod.number().optional(),
          name: zod
            .string()
            .min(putSellerBodyProductsItemCategoryNameMin)
            .max(putSellerBodyProductsItemCategoryNameMax),
          version: zod.number().optional(),
        }),
        images: zod
          .array(
            zod.object({
              id: zod.number().optional(),
              fileName: zod.string().optional(),
              contentType: zod.string().optional(),
              downloadUrl: zod.string(),
            }),
          )
          .optional(),
        version: zod.number().optional(),
        auditMetaData: zod
          .object({
            createdBy: zod.string().optional(),
            createdDate: zod.iso.datetime({}).optional(),
            lastModifiedBy: zod.string().optional(),
            lastModifiedDate: zod.iso.datetime({}).optional(),
          })
          .optional(),
      }),
    )
    .optional(),
});

export const PatchSellerParams = zod.object({
  id: zod.number(),
});

export const patchSellerBodyAddressesItemStreetMin = 5;
export const patchSellerBodyAddressesItemStreetMax = 2147483647;

export const patchSellerBodyAddressesItemCityMin = 2;
export const patchSellerBodyAddressesItemCityMax = 2147483647;

export const patchSellerBodyAddressesItemStateMin = 2;
export const patchSellerBodyAddressesItemStateMax = 2147483647;

export const patchSellerBodyAddressesItemCountryMin = 2;
export const patchSellerBodyAddressesItemCountryMax = 2147483647;

export const patchSellerBodyAddressesItemPinCodeMin = 4;
export const patchSellerBodyAddressesItemPinCodeMax = 2147483647;

export const patchSellerBodyUserUsernameMax = 100;

export const patchSellerBodyUserPasswordMin = 2;
export const patchSellerBodyUserPasswordMax = 100;

export const patchSellerBodyUserEmailMin = 0;
export const patchSellerBodyUserEmailMax = 100;

export const patchSellerBodyProductsItemNameMin = 3;
export const patchSellerBodyProductsItemNameMax = 500;

export const patchSellerBodyProductsItemDescriptionMin = 10;
export const patchSellerBodyProductsItemDescriptionMax = 600;

export const patchSellerBodyProductsItemCategoryNameMin = 2;
export const patchSellerBodyProductsItemCategoryNameMax = 100;

export const PatchSellerBody = zod.object({
  id: zod.number().optional(),
  firstName: zod.string().optional(),
  lastName: zod.string().optional(),
  phone: zod.string().optional(),
  addresses: zod
    .array(
      zod.object({
        id: zod.number().optional(),
        addressType: zod.enum(["BILLING", "RESIDENTIAL", "POSTAL", "OFFICE", "SHIPPING"]).optional(),
        street: zod.string().min(patchSellerBodyAddressesItemStreetMin).max(patchSellerBodyAddressesItemStreetMax),
        city: zod.string().min(patchSellerBodyAddressesItemCityMin).max(patchSellerBodyAddressesItemCityMax),
        state: zod.string().min(patchSellerBodyAddressesItemStateMin).max(patchSellerBodyAddressesItemStateMax),
        country: zod.string().min(patchSellerBodyAddressesItemCountryMin).max(patchSellerBodyAddressesItemCountryMax),
        pinCode: zod.string().min(patchSellerBodyAddressesItemPinCodeMin).max(patchSellerBodyAddressesItemPinCodeMax),
        version: zod.number().optional(),
        auditMetaData: zod
          .object({
            createdBy: zod.string().optional(),
            createdDate: zod.iso.datetime({}).optional(),
            lastModifiedBy: zod.string().optional(),
            lastModifiedDate: zod.iso.datetime({}).optional(),
          })
          .optional(),
      }),
    )
    .optional(),
  user: zod
    .object({
      id: zod.number().optional(),
      username: zod.string().min(1).max(patchSellerBodyUserUsernameMax),
      password: zod.string().min(patchSellerBodyUserPasswordMin).max(patchSellerBodyUserPasswordMax),
      email: zod.email().min(patchSellerBodyUserEmailMin).max(patchSellerBodyUserEmailMax),
      enabled: zod.boolean().optional(),
      roles: zod
        .array(
          zod.object({
            id: zod.number().optional(),
            role: zod.enum(["ROLE_CUSTOMER", "ROLE_USER", "ROLE_SELLER", "ROLE_ADMIN", "ROLE_MODERATOR"]).optional(),
          }),
        )
        .optional(),
      accountNonExpired: zod.boolean().optional(),
      credentialsNonExpired: zod.boolean().optional(),
      accountNonLocked: zod.boolean().optional(),
    })
    .optional(),
  version: zod.number().optional(),
  auditMetaData: zod
    .object({
      createdBy: zod.string().optional(),
      createdDate: zod.iso.datetime({}).optional(),
      lastModifiedBy: zod.string().optional(),
      lastModifiedDate: zod.iso.datetime({}).optional(),
    })
    .optional(),
  products: zod
    .array(
      zod.object({
        id: zod.number().optional(),
        name: zod.string().min(patchSellerBodyProductsItemNameMin).max(patchSellerBodyProductsItemNameMax),
        description: zod
          .string()
          .min(patchSellerBodyProductsItemDescriptionMin)
          .max(patchSellerBodyProductsItemDescriptionMax),
        price: zod.number().optional(),
        discountedPrice: zod.number().optional(),
        stock: zod.number().optional(),
        category: zod.object({
          id: zod.number().optional(),
          name: zod
            .string()
            .min(patchSellerBodyProductsItemCategoryNameMin)
            .max(patchSellerBodyProductsItemCategoryNameMax),
          version: zod.number().optional(),
        }),
        images: zod
          .array(
            zod.object({
              id: zod.number().optional(),
              fileName: zod.string().optional(),
              contentType: zod.string().optional(),
              downloadUrl: zod.string(),
            }),
          )
          .optional(),
        version: zod.number().optional(),
        auditMetaData: zod
          .object({
            createdBy: zod.string().optional(),
            createdDate: zod.iso.datetime({}).optional(),
            lastModifiedBy: zod.string().optional(),
            lastModifiedDate: zod.iso.datetime({}).optional(),
          })
          .optional(),
      }),
    )
    .optional(),
});

export const UpdateAddressParams = zod.object({
  id: zod.number(),
  addressId: zod.number(),
});

export const updateAddressBodyStreetMin = 5;
export const updateAddressBodyStreetMax = 2147483647;

export const updateAddressBodyCityMin = 2;
export const updateAddressBodyCityMax = 2147483647;

export const updateAddressBodyStateMin = 2;
export const updateAddressBodyStateMax = 2147483647;

export const updateAddressBodyCountryMin = 2;
export const updateAddressBodyCountryMax = 2147483647;

export const updateAddressBodyPinCodeMin = 4;
export const updateAddressBodyPinCodeMax = 2147483647;

export const UpdateAddressBody = zod.object({
  id: zod.number().optional(),
  addressType: zod.enum(["BILLING", "RESIDENTIAL", "POSTAL", "OFFICE", "SHIPPING"]).optional(),
  street: zod.string().min(updateAddressBodyStreetMin).max(updateAddressBodyStreetMax),
  city: zod.string().min(updateAddressBodyCityMin).max(updateAddressBodyCityMax),
  state: zod.string().min(updateAddressBodyStateMin).max(updateAddressBodyStateMax),
  country: zod.string().min(updateAddressBodyCountryMin).max(updateAddressBodyCountryMax),
  pinCode: zod.string().min(updateAddressBodyPinCodeMin).max(updateAddressBodyPinCodeMax),
  version: zod.number().optional(),
  auditMetaData: zod
    .object({
      createdBy: zod.string().optional(),
      createdDate: zod.iso.datetime({}).optional(),
      lastModifiedBy: zod.string().optional(),
      lastModifiedDate: zod.iso.datetime({}).optional(),
    })
    .optional(),
});

export const DeleteAddressParams = zod.object({
  id: zod.number(),
  addressId: zod.number(),
});

export const GetProductByIdParams = zod.object({
  id: zod.number(),
});

/**
 * @summary Update a product (Put operation)
 */
export const PutProductParams = zod.object({
  id: zod.number(),
});

export const putProductBodyNameMin = 3;
export const putProductBodyNameMax = 500;

export const putProductBodyDescriptionMin = 10;
export const putProductBodyDescriptionMax = 600;

export const putProductBodyCategoryNameMin = 2;
export const putProductBodyCategoryNameMax = 100;

export const PutProductBody = zod.object({
  id: zod.number().optional(),
  name: zod.string().min(putProductBodyNameMin).max(putProductBodyNameMax),
  description: zod.string().min(putProductBodyDescriptionMin).max(putProductBodyDescriptionMax),
  price: zod.number().optional(),
  discountedPrice: zod.number().optional(),
  stock: zod.number().optional(),
  category: zod.object({
    id: zod.number().optional(),
    name: zod.string().min(putProductBodyCategoryNameMin).max(putProductBodyCategoryNameMax),
    version: zod.number().optional(),
  }),
  images: zod
    .array(
      zod.object({
        id: zod.number().optional(),
        fileName: zod.string().optional(),
        contentType: zod.string().optional(),
        downloadUrl: zod.string(),
      }),
    )
    .optional(),
  version: zod.number().optional(),
  auditMetaData: zod
    .object({
      createdBy: zod.string().optional(),
      createdDate: zod.iso.datetime({}).optional(),
      lastModifiedBy: zod.string().optional(),
      lastModifiedDate: zod.iso.datetime({}).optional(),
    })
    .optional(),
});

export const DeleteProductByIdParams = zod.object({
  id: zod.number(),
});

export const PatchProductParams = zod.object({
  id: zod.number(),
});

export const patchProductBodyNameMin = 3;
export const patchProductBodyNameMax = 500;

export const patchProductBodyDescriptionMin = 10;
export const patchProductBodyDescriptionMax = 600;

export const patchProductBodyCategoryNameMin = 2;
export const patchProductBodyCategoryNameMax = 100;

export const PatchProductBody = zod.object({
  id: zod.number().optional(),
  name: zod.string().min(patchProductBodyNameMin).max(patchProductBodyNameMax),
  description: zod.string().min(patchProductBodyDescriptionMin).max(patchProductBodyDescriptionMax),
  price: zod.number().optional(),
  discountedPrice: zod.number().optional(),
  stock: zod.number().optional(),
  category: zod.object({
    id: zod.number().optional(),
    name: zod.string().min(patchProductBodyCategoryNameMin).max(patchProductBodyCategoryNameMax),
    version: zod.number().optional(),
  }),
  images: zod
    .array(
      zod.object({
        id: zod.number().optional(),
        fileName: zod.string().optional(),
        contentType: zod.string().optional(),
        downloadUrl: zod.string(),
      }),
    )
    .optional(),
  version: zod.number().optional(),
  auditMetaData: zod
    .object({
      createdBy: zod.string().optional(),
      createdDate: zod.iso.datetime({}).optional(),
      lastModifiedBy: zod.string().optional(),
      lastModifiedDate: zod.iso.datetime({}).optional(),
    })
    .optional(),
});

export const UpdateImageParams = zod.object({
  imageId: zod.number(),
});

export const UpdateImageBody = zod.object({
  files: zod.instanceof(File),
});

export const GetCustomerByIdParams = zod.object({
  id: zod.number(),
});

/**
 * @summary Update a customer (PUT operation)
 */
export const PutCustomerParams = zod.object({
  id: zod.number(),
});

export const putCustomerBodyAddressesItemStreetMin = 5;
export const putCustomerBodyAddressesItemStreetMax = 2147483647;

export const putCustomerBodyAddressesItemCityMin = 2;
export const putCustomerBodyAddressesItemCityMax = 2147483647;

export const putCustomerBodyAddressesItemStateMin = 2;
export const putCustomerBodyAddressesItemStateMax = 2147483647;

export const putCustomerBodyAddressesItemCountryMin = 2;
export const putCustomerBodyAddressesItemCountryMax = 2147483647;

export const putCustomerBodyAddressesItemPinCodeMin = 4;
export const putCustomerBodyAddressesItemPinCodeMax = 2147483647;

export const putCustomerBodyUserUsernameMax = 100;

export const putCustomerBodyUserPasswordMin = 2;
export const putCustomerBodyUserPasswordMax = 100;

export const putCustomerBodyUserEmailMin = 0;
export const putCustomerBodyUserEmailMax = 100;

export const putCustomerBodyCartCartItemsItemProductNameMin = 3;
export const putCustomerBodyCartCartItemsItemProductNameMax = 500;

export const putCustomerBodyCartCartItemsItemProductDescriptionMin = 10;
export const putCustomerBodyCartCartItemsItemProductDescriptionMax = 600;

export const putCustomerBodyCartCartItemsItemProductCategoryNameMin = 2;
export const putCustomerBodyCartCartItemsItemProductCategoryNameMax = 100;

export const putCustomerBodyOrdersItemOrderItemsItemProductNameMin = 3;
export const putCustomerBodyOrdersItemOrderItemsItemProductNameMax = 500;

export const putCustomerBodyOrdersItemOrderItemsItemProductDescriptionMin = 10;
export const putCustomerBodyOrdersItemOrderItemsItemProductDescriptionMax = 600;

export const putCustomerBodyOrdersItemOrderItemsItemProductCategoryNameMin = 2;
export const putCustomerBodyOrdersItemOrderItemsItemProductCategoryNameMax = 100;

export const PutCustomerBody = zod.object({
  id: zod.number().optional(),
  firstName: zod.string().optional(),
  lastName: zod.string().optional(),
  phone: zod.string().optional(),
  addresses: zod
    .array(
      zod.object({
        id: zod.number().optional(),
        addressType: zod.enum(["BILLING", "RESIDENTIAL", "POSTAL", "OFFICE", "SHIPPING"]).optional(),
        street: zod.string().min(putCustomerBodyAddressesItemStreetMin).max(putCustomerBodyAddressesItemStreetMax),
        city: zod.string().min(putCustomerBodyAddressesItemCityMin).max(putCustomerBodyAddressesItemCityMax),
        state: zod.string().min(putCustomerBodyAddressesItemStateMin).max(putCustomerBodyAddressesItemStateMax),
        country: zod.string().min(putCustomerBodyAddressesItemCountryMin).max(putCustomerBodyAddressesItemCountryMax),
        pinCode: zod.string().min(putCustomerBodyAddressesItemPinCodeMin).max(putCustomerBodyAddressesItemPinCodeMax),
        version: zod.number().optional(),
        auditMetaData: zod
          .object({
            createdBy: zod.string().optional(),
            createdDate: zod.iso.datetime({}).optional(),
            lastModifiedBy: zod.string().optional(),
            lastModifiedDate: zod.iso.datetime({}).optional(),
          })
          .optional(),
      }),
    )
    .optional(),
  user: zod
    .object({
      id: zod.number().optional(),
      username: zod.string().min(1).max(putCustomerBodyUserUsernameMax),
      password: zod.string().min(putCustomerBodyUserPasswordMin).max(putCustomerBodyUserPasswordMax),
      email: zod.email().min(putCustomerBodyUserEmailMin).max(putCustomerBodyUserEmailMax),
      enabled: zod.boolean().optional(),
      roles: zod
        .array(
          zod.object({
            id: zod.number().optional(),
            role: zod.enum(["ROLE_CUSTOMER", "ROLE_USER", "ROLE_SELLER", "ROLE_ADMIN", "ROLE_MODERATOR"]).optional(),
          }),
        )
        .optional(),
      accountNonExpired: zod.boolean().optional(),
      credentialsNonExpired: zod.boolean().optional(),
      accountNonLocked: zod.boolean().optional(),
    })
    .optional(),
  version: zod.number().optional(),
  auditMetaData: zod
    .object({
      createdBy: zod.string().optional(),
      createdDate: zod.iso.datetime({}).optional(),
      lastModifiedBy: zod.string().optional(),
      lastModifiedDate: zod.iso.datetime({}).optional(),
    })
    .optional(),
  cart: zod
    .object({
      id: zod.number().optional(),
      cartItems: zod
        .array(
          zod.object({
            id: zod.number().optional(),
            product: zod
              .object({
                id: zod.number().optional(),
                name: zod
                  .string()
                  .min(putCustomerBodyCartCartItemsItemProductNameMin)
                  .max(putCustomerBodyCartCartItemsItemProductNameMax),
                description: zod
                  .string()
                  .min(putCustomerBodyCartCartItemsItemProductDescriptionMin)
                  .max(putCustomerBodyCartCartItemsItemProductDescriptionMax),
                price: zod.number().optional(),
                discountedPrice: zod.number().optional(),
                stock: zod.number().optional(),
                category: zod.object({
                  id: zod.number().optional(),
                  name: zod
                    .string()
                    .min(putCustomerBodyCartCartItemsItemProductCategoryNameMin)
                    .max(putCustomerBodyCartCartItemsItemProductCategoryNameMax),
                  version: zod.number().optional(),
                }),
                images: zod
                  .array(
                    zod.object({
                      id: zod.number().optional(),
                      fileName: zod.string().optional(),
                      contentType: zod.string().optional(),
                      downloadUrl: zod.string(),
                    }),
                  )
                  .optional(),
                version: zod.number().optional(),
                auditMetaData: zod
                  .object({
                    createdBy: zod.string().optional(),
                    createdDate: zod.iso.datetime({}).optional(),
                    lastModifiedBy: zod.string().optional(),
                    lastModifiedDate: zod.iso.datetime({}).optional(),
                  })
                  .optional(),
              })
              .optional(),
            quantity: zod.number().optional(),
            price: zod.number().optional(),
            discount: zod.number().optional(),
            auditMetaData: zod
              .object({
                createdBy: zod.string().optional(),
                createdDate: zod.iso.datetime({}).optional(),
                lastModifiedBy: zod.string().optional(),
                lastModifiedDate: zod.iso.datetime({}).optional(),
              })
              .optional(),
            discountedPrice: zod.number().optional(),
          }),
        )
        .optional(),
      totalPrice: zod.number().optional(),
      auditMetaData: zod
        .object({
          createdBy: zod.string().optional(),
          createdDate: zod.iso.datetime({}).optional(),
          lastModifiedBy: zod.string().optional(),
          lastModifiedDate: zod.iso.datetime({}).optional(),
        })
        .optional(),
    })
    .optional(),
  orders: zod
    .array(
      zod.object({
        id: zod.number().optional(),
        orderId: zod.uuid().optional(),
        orderStatus: zod.enum(["NEW", "PENDING", "SHIPPED", "COMPLETED", "CANCELLED"]).optional(),
        payment: zod
          .object({
            id: zod.number().optional(),
            paymentIdentifier: zod.uuid().optional(),
            paymentType: zod.enum(["CREDIT_CARD", "CASH", "PAYPAL", "BANK_TRANSFER"]).optional(),
            paymentStatus: zod.enum(["PENDING", "CREATED", "COMPLETED", "FAILED", "CANCELLED"]).optional(),
            paymentDetails: zod
              .object({
                cardHolderName: zod.string().optional(),
                cardType: zod.string().optional(),
                cardNumber: zod.string().optional(),
                expiryDate: zod.string().optional(),
                cvv: zod.string().optional(),
              })
              .optional(),
            amount: zod.number().optional(),
            paymentGatewayName: zod.string().optional(),
            paymentGatewayStatus: zod.string().optional(),
            paymentGatewayMessage: zod.string().optional(),
            paymentGatewayErrorDescription: zod.string().optional(),
            version: zod.number().optional(),
          })
          .optional(),
        orderItems: zod
          .array(
            zod.object({
              id: zod.number().optional(),
              product: zod
                .object({
                  id: zod.number().optional(),
                  name: zod
                    .string()
                    .min(putCustomerBodyOrdersItemOrderItemsItemProductNameMin)
                    .max(putCustomerBodyOrdersItemOrderItemsItemProductNameMax),
                  description: zod
                    .string()
                    .min(putCustomerBodyOrdersItemOrderItemsItemProductDescriptionMin)
                    .max(putCustomerBodyOrdersItemOrderItemsItemProductDescriptionMax),
                  price: zod.number().optional(),
                  discountedPrice: zod.number().optional(),
                  stock: zod.number().optional(),
                  category: zod.object({
                    id: zod.number().optional(),
                    name: zod
                      .string()
                      .min(putCustomerBodyOrdersItemOrderItemsItemProductCategoryNameMin)
                      .max(putCustomerBodyOrdersItemOrderItemsItemProductCategoryNameMax),
                    version: zod.number().optional(),
                  }),
                  images: zod
                    .array(
                      zod.object({
                        id: zod.number().optional(),
                        fileName: zod.string().optional(),
                        contentType: zod.string().optional(),
                        downloadUrl: zod.string(),
                      }),
                    )
                    .optional(),
                  version: zod.number().optional(),
                  auditMetaData: zod
                    .object({
                      createdBy: zod.string().optional(),
                      createdDate: zod.iso.datetime({}).optional(),
                      lastModifiedBy: zod.string().optional(),
                      lastModifiedDate: zod.iso.datetime({}).optional(),
                    })
                    .optional(),
                })
                .optional(),
              quantity: zod.number().optional(),
              orderItemTotalPrice: zod.number().optional(),
              version: zod.number().optional(),
              auditMetaData: zod
                .object({
                  createdBy: zod.string().optional(),
                  createdDate: zod.iso.datetime({}).optional(),
                  lastModifiedBy: zod.string().optional(),
                  lastModifiedDate: zod.iso.datetime({}).optional(),
                })
                .optional(),
            }),
          )
          .optional(),
        totalPrice: zod.number().optional(),
        shippingPrice: zod.number().optional(),
        version: zod.number().optional(),
      }),
    )
    .optional(),
});

/**
 * @summary Update a customer (PATCH operation)
 */
export const PatchCustomerParams = zod.object({
  id: zod.number(),
});

export const patchCustomerBodyAddressesItemStreetMin = 5;
export const patchCustomerBodyAddressesItemStreetMax = 2147483647;

export const patchCustomerBodyAddressesItemCityMin = 2;
export const patchCustomerBodyAddressesItemCityMax = 2147483647;

export const patchCustomerBodyAddressesItemStateMin = 2;
export const patchCustomerBodyAddressesItemStateMax = 2147483647;

export const patchCustomerBodyAddressesItemCountryMin = 2;
export const patchCustomerBodyAddressesItemCountryMax = 2147483647;

export const patchCustomerBodyAddressesItemPinCodeMin = 4;
export const patchCustomerBodyAddressesItemPinCodeMax = 2147483647;

export const patchCustomerBodyUserUsernameMax = 100;

export const patchCustomerBodyUserPasswordMin = 2;
export const patchCustomerBodyUserPasswordMax = 100;

export const patchCustomerBodyUserEmailMin = 0;
export const patchCustomerBodyUserEmailMax = 100;

export const patchCustomerBodyCartCartItemsItemProductNameMin = 3;
export const patchCustomerBodyCartCartItemsItemProductNameMax = 500;

export const patchCustomerBodyCartCartItemsItemProductDescriptionMin = 10;
export const patchCustomerBodyCartCartItemsItemProductDescriptionMax = 600;

export const patchCustomerBodyCartCartItemsItemProductCategoryNameMin = 2;
export const patchCustomerBodyCartCartItemsItemProductCategoryNameMax = 100;

export const patchCustomerBodyOrdersItemOrderItemsItemProductNameMin = 3;
export const patchCustomerBodyOrdersItemOrderItemsItemProductNameMax = 500;

export const patchCustomerBodyOrdersItemOrderItemsItemProductDescriptionMin = 10;
export const patchCustomerBodyOrdersItemOrderItemsItemProductDescriptionMax = 600;

export const patchCustomerBodyOrdersItemOrderItemsItemProductCategoryNameMin = 2;
export const patchCustomerBodyOrdersItemOrderItemsItemProductCategoryNameMax = 100;

export const PatchCustomerBody = zod.object({
  id: zod.number().optional(),
  firstName: zod.string().optional(),
  lastName: zod.string().optional(),
  phone: zod.string().optional(),
  addresses: zod
    .array(
      zod.object({
        id: zod.number().optional(),
        addressType: zod.enum(["BILLING", "RESIDENTIAL", "POSTAL", "OFFICE", "SHIPPING"]).optional(),
        street: zod.string().min(patchCustomerBodyAddressesItemStreetMin).max(patchCustomerBodyAddressesItemStreetMax),
        city: zod.string().min(patchCustomerBodyAddressesItemCityMin).max(patchCustomerBodyAddressesItemCityMax),
        state: zod.string().min(patchCustomerBodyAddressesItemStateMin).max(patchCustomerBodyAddressesItemStateMax),
        country: zod
          .string()
          .min(patchCustomerBodyAddressesItemCountryMin)
          .max(patchCustomerBodyAddressesItemCountryMax),
        pinCode: zod
          .string()
          .min(patchCustomerBodyAddressesItemPinCodeMin)
          .max(patchCustomerBodyAddressesItemPinCodeMax),
        version: zod.number().optional(),
        auditMetaData: zod
          .object({
            createdBy: zod.string().optional(),
            createdDate: zod.iso.datetime({}).optional(),
            lastModifiedBy: zod.string().optional(),
            lastModifiedDate: zod.iso.datetime({}).optional(),
          })
          .optional(),
      }),
    )
    .optional(),
  user: zod
    .object({
      id: zod.number().optional(),
      username: zod.string().min(1).max(patchCustomerBodyUserUsernameMax),
      password: zod.string().min(patchCustomerBodyUserPasswordMin).max(patchCustomerBodyUserPasswordMax),
      email: zod.email().min(patchCustomerBodyUserEmailMin).max(patchCustomerBodyUserEmailMax),
      enabled: zod.boolean().optional(),
      roles: zod
        .array(
          zod.object({
            id: zod.number().optional(),
            role: zod.enum(["ROLE_CUSTOMER", "ROLE_USER", "ROLE_SELLER", "ROLE_ADMIN", "ROLE_MODERATOR"]).optional(),
          }),
        )
        .optional(),
      accountNonExpired: zod.boolean().optional(),
      credentialsNonExpired: zod.boolean().optional(),
      accountNonLocked: zod.boolean().optional(),
    })
    .optional(),
  version: zod.number().optional(),
  auditMetaData: zod
    .object({
      createdBy: zod.string().optional(),
      createdDate: zod.iso.datetime({}).optional(),
      lastModifiedBy: zod.string().optional(),
      lastModifiedDate: zod.iso.datetime({}).optional(),
    })
    .optional(),
  cart: zod
    .object({
      id: zod.number().optional(),
      cartItems: zod
        .array(
          zod.object({
            id: zod.number().optional(),
            product: zod
              .object({
                id: zod.number().optional(),
                name: zod
                  .string()
                  .min(patchCustomerBodyCartCartItemsItemProductNameMin)
                  .max(patchCustomerBodyCartCartItemsItemProductNameMax),
                description: zod
                  .string()
                  .min(patchCustomerBodyCartCartItemsItemProductDescriptionMin)
                  .max(patchCustomerBodyCartCartItemsItemProductDescriptionMax),
                price: zod.number().optional(),
                discountedPrice: zod.number().optional(),
                stock: zod.number().optional(),
                category: zod.object({
                  id: zod.number().optional(),
                  name: zod
                    .string()
                    .min(patchCustomerBodyCartCartItemsItemProductCategoryNameMin)
                    .max(patchCustomerBodyCartCartItemsItemProductCategoryNameMax),
                  version: zod.number().optional(),
                }),
                images: zod
                  .array(
                    zod.object({
                      id: zod.number().optional(),
                      fileName: zod.string().optional(),
                      contentType: zod.string().optional(),
                      downloadUrl: zod.string(),
                    }),
                  )
                  .optional(),
                version: zod.number().optional(),
                auditMetaData: zod
                  .object({
                    createdBy: zod.string().optional(),
                    createdDate: zod.iso.datetime({}).optional(),
                    lastModifiedBy: zod.string().optional(),
                    lastModifiedDate: zod.iso.datetime({}).optional(),
                  })
                  .optional(),
              })
              .optional(),
            quantity: zod.number().optional(),
            price: zod.number().optional(),
            discount: zod.number().optional(),
            auditMetaData: zod
              .object({
                createdBy: zod.string().optional(),
                createdDate: zod.iso.datetime({}).optional(),
                lastModifiedBy: zod.string().optional(),
                lastModifiedDate: zod.iso.datetime({}).optional(),
              })
              .optional(),
            discountedPrice: zod.number().optional(),
          }),
        )
        .optional(),
      totalPrice: zod.number().optional(),
      auditMetaData: zod
        .object({
          createdBy: zod.string().optional(),
          createdDate: zod.iso.datetime({}).optional(),
          lastModifiedBy: zod.string().optional(),
          lastModifiedDate: zod.iso.datetime({}).optional(),
        })
        .optional(),
    })
    .optional(),
  orders: zod
    .array(
      zod.object({
        id: zod.number().optional(),
        orderId: zod.uuid().optional(),
        orderStatus: zod.enum(["NEW", "PENDING", "SHIPPED", "COMPLETED", "CANCELLED"]).optional(),
        payment: zod
          .object({
            id: zod.number().optional(),
            paymentIdentifier: zod.uuid().optional(),
            paymentType: zod.enum(["CREDIT_CARD", "CASH", "PAYPAL", "BANK_TRANSFER"]).optional(),
            paymentStatus: zod.enum(["PENDING", "CREATED", "COMPLETED", "FAILED", "CANCELLED"]).optional(),
            paymentDetails: zod
              .object({
                cardHolderName: zod.string().optional(),
                cardType: zod.string().optional(),
                cardNumber: zod.string().optional(),
                expiryDate: zod.string().optional(),
                cvv: zod.string().optional(),
              })
              .optional(),
            amount: zod.number().optional(),
            paymentGatewayName: zod.string().optional(),
            paymentGatewayStatus: zod.string().optional(),
            paymentGatewayMessage: zod.string().optional(),
            paymentGatewayErrorDescription: zod.string().optional(),
            version: zod.number().optional(),
          })
          .optional(),
        orderItems: zod
          .array(
            zod.object({
              id: zod.number().optional(),
              product: zod
                .object({
                  id: zod.number().optional(),
                  name: zod
                    .string()
                    .min(patchCustomerBodyOrdersItemOrderItemsItemProductNameMin)
                    .max(patchCustomerBodyOrdersItemOrderItemsItemProductNameMax),
                  description: zod
                    .string()
                    .min(patchCustomerBodyOrdersItemOrderItemsItemProductDescriptionMin)
                    .max(patchCustomerBodyOrdersItemOrderItemsItemProductDescriptionMax),
                  price: zod.number().optional(),
                  discountedPrice: zod.number().optional(),
                  stock: zod.number().optional(),
                  category: zod.object({
                    id: zod.number().optional(),
                    name: zod
                      .string()
                      .min(patchCustomerBodyOrdersItemOrderItemsItemProductCategoryNameMin)
                      .max(patchCustomerBodyOrdersItemOrderItemsItemProductCategoryNameMax),
                    version: zod.number().optional(),
                  }),
                  images: zod
                    .array(
                      zod.object({
                        id: zod.number().optional(),
                        fileName: zod.string().optional(),
                        contentType: zod.string().optional(),
                        downloadUrl: zod.string(),
                      }),
                    )
                    .optional(),
                  version: zod.number().optional(),
                  auditMetaData: zod
                    .object({
                      createdBy: zod.string().optional(),
                      createdDate: zod.iso.datetime({}).optional(),
                      lastModifiedBy: zod.string().optional(),
                      lastModifiedDate: zod.iso.datetime({}).optional(),
                    })
                    .optional(),
                })
                .optional(),
              quantity: zod.number().optional(),
              orderItemTotalPrice: zod.number().optional(),
              version: zod.number().optional(),
              auditMetaData: zod
                .object({
                  createdBy: zod.string().optional(),
                  createdDate: zod.iso.datetime({}).optional(),
                  lastModifiedBy: zod.string().optional(),
                  lastModifiedDate: zod.iso.datetime({}).optional(),
                })
                .optional(),
            }),
          )
          .optional(),
        totalPrice: zod.number().optional(),
        shippingPrice: zod.number().optional(),
        version: zod.number().optional(),
      }),
    )
    .optional(),
});

export const UpdateAddress1Params = zod.object({
  id: zod.number(),
  addressId: zod.number(),
});

export const updateAddress1BodyStreetMin = 5;
export const updateAddress1BodyStreetMax = 2147483647;

export const updateAddress1BodyCityMin = 2;
export const updateAddress1BodyCityMax = 2147483647;

export const updateAddress1BodyStateMin = 2;
export const updateAddress1BodyStateMax = 2147483647;

export const updateAddress1BodyCountryMin = 2;
export const updateAddress1BodyCountryMax = 2147483647;

export const updateAddress1BodyPinCodeMin = 4;
export const updateAddress1BodyPinCodeMax = 2147483647;

export const UpdateAddress1Body = zod.object({
  id: zod.number().optional(),
  addressType: zod.enum(["BILLING", "RESIDENTIAL", "POSTAL", "OFFICE", "SHIPPING"]).optional(),
  street: zod.string().min(updateAddress1BodyStreetMin).max(updateAddress1BodyStreetMax),
  city: zod.string().min(updateAddress1BodyCityMin).max(updateAddress1BodyCityMax),
  state: zod.string().min(updateAddress1BodyStateMin).max(updateAddress1BodyStateMax),
  country: zod.string().min(updateAddress1BodyCountryMin).max(updateAddress1BodyCountryMax),
  pinCode: zod.string().min(updateAddress1BodyPinCodeMin).max(updateAddress1BodyPinCodeMax),
  version: zod.number().optional(),
  auditMetaData: zod
    .object({
      createdBy: zod.string().optional(),
      createdDate: zod.iso.datetime({}).optional(),
      lastModifiedBy: zod.string().optional(),
      lastModifiedDate: zod.iso.datetime({}).optional(),
    })
    .optional(),
});

export const DeleteAddress1Params = zod.object({
  id: zod.number(),
  addressId: zod.number(),
});

export const GetCategoryByIdParams = zod.object({
  id: zod.number(),
});

/**
 * @summary Update a category (Put operation)
 */
export const PutCategoryParams = zod.object({
  id: zod.number(),
});

export const putCategoryBodyNameMin = 2;
export const putCategoryBodyNameMax = 100;

export const PutCategoryBody = zod.object({
  id: zod.number().optional(),
  name: zod.string().min(putCategoryBodyNameMin).max(putCategoryBodyNameMax),
  version: zod.number().optional(),
});

export const DeleteCategoryByIdParams = zod.object({
  id: zod.number(),
});

export const PatchCategoryParams = zod.object({
  id: zod.number(),
});

export const patchCategoryBodyNameMin = 2;
export const patchCategoryBodyNameMax = 100;

export const PatchCategoryBody = zod.object({
  id: zod.number().optional(),
  name: zod.string().min(patchCategoryBodyNameMin).max(patchCategoryBodyNameMax),
  version: zod.number().optional(),
});

export const patchCartQueryQuantityExclusiveMin = 0;

export const PatchCartQueryParams = zod.object({
  productId: zod.number(),
  quantity: zod.number().gt(patchCartQueryQuantityExclusiveMin),
});

/**
 * @summary Add product to cart
 */
export const addProductToCartQueryQuantityExclusiveMin = 0;

export const AddProductToCartQueryParams = zod.object({
  productId: zod.number(),
  quantity: zod.number().gt(addProductToCartQueryQuantityExclusiveMin),
});

export const AddAddressesParams = zod.object({
  id: zod.number(),
});

export const addAddressesBodyStreetMin = 5;
export const addAddressesBodyStreetMax = 2147483647;

export const addAddressesBodyCityMin = 2;
export const addAddressesBodyCityMax = 2147483647;

export const addAddressesBodyStateMin = 2;
export const addAddressesBodyStateMax = 2147483647;

export const addAddressesBodyCountryMin = 2;
export const addAddressesBodyCountryMax = 2147483647;

export const addAddressesBodyPinCodeMin = 4;
export const addAddressesBodyPinCodeMax = 2147483647;

export const AddAddressesBodyItem = zod.object({
  id: zod.number().optional(),
  addressType: zod.enum(["BILLING", "RESIDENTIAL", "POSTAL", "OFFICE", "SHIPPING"]).optional(),
  street: zod.string().min(addAddressesBodyStreetMin).max(addAddressesBodyStreetMax),
  city: zod.string().min(addAddressesBodyCityMin).max(addAddressesBodyCityMax),
  state: zod.string().min(addAddressesBodyStateMin).max(addAddressesBodyStateMax),
  country: zod.string().min(addAddressesBodyCountryMin).max(addAddressesBodyCountryMax),
  pinCode: zod.string().min(addAddressesBodyPinCodeMin).max(addAddressesBodyPinCodeMax),
  version: zod.number().optional(),
  auditMetaData: zod
    .object({
      createdBy: zod.string().optional(),
      createdDate: zod.iso.datetime({}).optional(),
      lastModifiedBy: zod.string().optional(),
      lastModifiedDate: zod.iso.datetime({}).optional(),
    })
    .optional(),
});
export const AddAddressesBody = zod.array(AddAddressesBodyItem);

export const createSellerBodyAddressesItemStreetMin = 5;
export const createSellerBodyAddressesItemStreetMax = 2147483647;

export const createSellerBodyAddressesItemCityMin = 2;
export const createSellerBodyAddressesItemCityMax = 2147483647;

export const createSellerBodyAddressesItemStateMin = 2;
export const createSellerBodyAddressesItemStateMax = 2147483647;

export const createSellerBodyAddressesItemCountryMin = 2;
export const createSellerBodyAddressesItemCountryMax = 2147483647;

export const createSellerBodyAddressesItemPinCodeMin = 4;
export const createSellerBodyAddressesItemPinCodeMax = 2147483647;

export const createSellerBodyUserUsernameMax = 100;

export const createSellerBodyUserPasswordMin = 2;
export const createSellerBodyUserPasswordMax = 100;

export const createSellerBodyUserEmailMin = 0;
export const createSellerBodyUserEmailMax = 100;

export const createSellerBodyProductsItemNameMin = 3;
export const createSellerBodyProductsItemNameMax = 500;

export const createSellerBodyProductsItemDescriptionMin = 10;
export const createSellerBodyProductsItemDescriptionMax = 600;

export const createSellerBodyProductsItemCategoryNameMin = 2;
export const createSellerBodyProductsItemCategoryNameMax = 100;

export const CreateSellerBody = zod.object({
  id: zod.number().optional(),
  firstName: zod.string().optional(),
  lastName: zod.string().optional(),
  phone: zod.string().optional(),
  addresses: zod
    .array(
      zod.object({
        id: zod.number().optional(),
        addressType: zod.enum(["BILLING", "RESIDENTIAL", "POSTAL", "OFFICE", "SHIPPING"]).optional(),
        street: zod.string().min(createSellerBodyAddressesItemStreetMin).max(createSellerBodyAddressesItemStreetMax),
        city: zod.string().min(createSellerBodyAddressesItemCityMin).max(createSellerBodyAddressesItemCityMax),
        state: zod.string().min(createSellerBodyAddressesItemStateMin).max(createSellerBodyAddressesItemStateMax),
        country: zod.string().min(createSellerBodyAddressesItemCountryMin).max(createSellerBodyAddressesItemCountryMax),
        pinCode: zod.string().min(createSellerBodyAddressesItemPinCodeMin).max(createSellerBodyAddressesItemPinCodeMax),
        version: zod.number().optional(),
        auditMetaData: zod
          .object({
            createdBy: zod.string().optional(),
            createdDate: zod.iso.datetime({}).optional(),
            lastModifiedBy: zod.string().optional(),
            lastModifiedDate: zod.iso.datetime({}).optional(),
          })
          .optional(),
      }),
    )
    .optional(),
  user: zod
    .object({
      id: zod.number().optional(),
      username: zod.string().min(1).max(createSellerBodyUserUsernameMax),
      password: zod.string().min(createSellerBodyUserPasswordMin).max(createSellerBodyUserPasswordMax),
      email: zod.email().min(createSellerBodyUserEmailMin).max(createSellerBodyUserEmailMax),
      enabled: zod.boolean().optional(),
      roles: zod
        .array(
          zod.object({
            id: zod.number().optional(),
            role: zod.enum(["ROLE_CUSTOMER", "ROLE_USER", "ROLE_SELLER", "ROLE_ADMIN", "ROLE_MODERATOR"]).optional(),
          }),
        )
        .optional(),
      accountNonExpired: zod.boolean().optional(),
      credentialsNonExpired: zod.boolean().optional(),
      accountNonLocked: zod.boolean().optional(),
    })
    .optional(),
  version: zod.number().optional(),
  auditMetaData: zod
    .object({
      createdBy: zod.string().optional(),
      createdDate: zod.iso.datetime({}).optional(),
      lastModifiedBy: zod.string().optional(),
      lastModifiedDate: zod.iso.datetime({}).optional(),
    })
    .optional(),
  products: zod
    .array(
      zod.object({
        id: zod.number().optional(),
        name: zod.string().min(createSellerBodyProductsItemNameMin).max(createSellerBodyProductsItemNameMax),
        description: zod
          .string()
          .min(createSellerBodyProductsItemDescriptionMin)
          .max(createSellerBodyProductsItemDescriptionMax),
        price: zod.number().optional(),
        discountedPrice: zod.number().optional(),
        stock: zod.number().optional(),
        category: zod.object({
          id: zod.number().optional(),
          name: zod
            .string()
            .min(createSellerBodyProductsItemCategoryNameMin)
            .max(createSellerBodyProductsItemCategoryNameMax),
          version: zod.number().optional(),
        }),
        images: zod
          .array(
            zod.object({
              id: zod.number().optional(),
              fileName: zod.string().optional(),
              contentType: zod.string().optional(),
              downloadUrl: zod.string(),
            }),
          )
          .optional(),
        version: zod.number().optional(),
        auditMetaData: zod
          .object({
            createdBy: zod.string().optional(),
            createdDate: zod.iso.datetime({}).optional(),
            lastModifiedBy: zod.string().optional(),
            lastModifiedDate: zod.iso.datetime({}).optional(),
          })
          .optional(),
      }),
    )
    .optional(),
});

export const saveProductBodyProductNameMin = 3;
export const saveProductBodyProductNameMax = 500;

export const saveProductBodyProductDescriptionMin = 10;
export const saveProductBodyProductDescriptionMax = 600;

export const saveProductBodyProductCategoryNameMin = 2;
export const saveProductBodyProductCategoryNameMax = 100;

export const SaveProductBody = zod.object({
  product: zod.object({
    id: zod.number().optional(),
    name: zod.string().min(saveProductBodyProductNameMin).max(saveProductBodyProductNameMax),
    description: zod.string().min(saveProductBodyProductDescriptionMin).max(saveProductBodyProductDescriptionMax),
    price: zod.number().optional(),
    discountedPrice: zod.number().optional(),
    stock: zod.number().optional(),
    category: zod.object({
      id: zod.number().optional(),
      name: zod.string().min(saveProductBodyProductCategoryNameMin).max(saveProductBodyProductCategoryNameMax),
      version: zod.number().optional(),
    }),
    images: zod
      .array(
        zod.object({
          id: zod.number().optional(),
          fileName: zod.string().optional(),
          contentType: zod.string().optional(),
          downloadUrl: zod.string(),
        }),
      )
      .optional(),
    version: zod.number().optional(),
    auditMetaData: zod
      .object({
        createdBy: zod.string().optional(),
        createdDate: zod.iso.datetime({}).optional(),
        lastModifiedBy: zod.string().optional(),
        lastModifiedDate: zod.iso.datetime({}).optional(),
      })
      .optional(),
  }),
  images: zod.array(zod.instanceof(File)).optional(),
});

/**
 * @summary Process a card payment
 */
export const ProcessCardPaymentBody = zod.object({
  cardHolderName: zod.string().optional(),
  cardType: zod.string().optional(),
  cardNumber: zod.string().optional(),
  expiryDate: zod.string().optional(),
  cvv: zod.string().optional(),
});

/**
 * @summary Create order
 */
export const CreateOrderQueryParams = zod.object({
  paymentIdentifier: zod.uuid(),
});

export const GetImagesByProductIdParams = zod.object({
  productId: zod.number(),
});

export const AddImagesToAProductParams = zod.object({
  productId: zod.number(),
});

export const addImagesToAProductQueryReplaceAllDefault = false;

export const AddImagesToAProductQueryParams = zod.object({
  replaceAll: zod.boolean().default(addImagesToAProductQueryReplaceAllDefault),
});

export const AddImagesToAProductBody = zod.object({
  files: zod.array(zod.instanceof(File)),
});

export const SaveImagesBody = zod.object({
  files: zod.array(zod.instanceof(File)),
});

export const SaveImageBody = zod.object({
  files: zod.instanceof(File),
});

export const AddAddresses1Params = zod.object({
  id: zod.number(),
});

export const addAddresses1BodyStreetMin = 5;
export const addAddresses1BodyStreetMax = 2147483647;

export const addAddresses1BodyCityMin = 2;
export const addAddresses1BodyCityMax = 2147483647;

export const addAddresses1BodyStateMin = 2;
export const addAddresses1BodyStateMax = 2147483647;

export const addAddresses1BodyCountryMin = 2;
export const addAddresses1BodyCountryMax = 2147483647;

export const addAddresses1BodyPinCodeMin = 4;
export const addAddresses1BodyPinCodeMax = 2147483647;

export const AddAddresses1BodyItem = zod.object({
  id: zod.number().optional(),
  addressType: zod.enum(["BILLING", "RESIDENTIAL", "POSTAL", "OFFICE", "SHIPPING"]).optional(),
  street: zod.string().min(addAddresses1BodyStreetMin).max(addAddresses1BodyStreetMax),
  city: zod.string().min(addAddresses1BodyCityMin).max(addAddresses1BodyCityMax),
  state: zod.string().min(addAddresses1BodyStateMin).max(addAddresses1BodyStateMax),
  country: zod.string().min(addAddresses1BodyCountryMin).max(addAddresses1BodyCountryMax),
  pinCode: zod.string().min(addAddresses1BodyPinCodeMin).max(addAddresses1BodyPinCodeMax),
  version: zod.number().optional(),
  auditMetaData: zod
    .object({
      createdBy: zod.string().optional(),
      createdDate: zod.iso.datetime({}).optional(),
      lastModifiedBy: zod.string().optional(),
      lastModifiedDate: zod.iso.datetime({}).optional(),
    })
    .optional(),
});
export const AddAddresses1Body = zod.array(AddAddresses1BodyItem);

export const createCustomerBodyAddressesItemStreetMin = 5;
export const createCustomerBodyAddressesItemStreetMax = 2147483647;

export const createCustomerBodyAddressesItemCityMin = 2;
export const createCustomerBodyAddressesItemCityMax = 2147483647;

export const createCustomerBodyAddressesItemStateMin = 2;
export const createCustomerBodyAddressesItemStateMax = 2147483647;

export const createCustomerBodyAddressesItemCountryMin = 2;
export const createCustomerBodyAddressesItemCountryMax = 2147483647;

export const createCustomerBodyAddressesItemPinCodeMin = 4;
export const createCustomerBodyAddressesItemPinCodeMax = 2147483647;

export const createCustomerBodyUserUsernameMax = 100;

export const createCustomerBodyUserPasswordMin = 2;
export const createCustomerBodyUserPasswordMax = 100;

export const createCustomerBodyUserEmailMin = 0;
export const createCustomerBodyUserEmailMax = 100;

export const createCustomerBodyCartCartItemsItemProductNameMin = 3;
export const createCustomerBodyCartCartItemsItemProductNameMax = 500;

export const createCustomerBodyCartCartItemsItemProductDescriptionMin = 10;
export const createCustomerBodyCartCartItemsItemProductDescriptionMax = 600;

export const createCustomerBodyCartCartItemsItemProductCategoryNameMin = 2;
export const createCustomerBodyCartCartItemsItemProductCategoryNameMax = 100;

export const createCustomerBodyOrdersItemOrderItemsItemProductNameMin = 3;
export const createCustomerBodyOrdersItemOrderItemsItemProductNameMax = 500;

export const createCustomerBodyOrdersItemOrderItemsItemProductDescriptionMin = 10;
export const createCustomerBodyOrdersItemOrderItemsItemProductDescriptionMax = 600;

export const createCustomerBodyOrdersItemOrderItemsItemProductCategoryNameMin = 2;
export const createCustomerBodyOrdersItemOrderItemsItemProductCategoryNameMax = 100;

export const CreateCustomerBody = zod.object({
  id: zod.number().optional(),
  firstName: zod.string().optional(),
  lastName: zod.string().optional(),
  phone: zod.string().optional(),
  addresses: zod
    .array(
      zod.object({
        id: zod.number().optional(),
        addressType: zod.enum(["BILLING", "RESIDENTIAL", "POSTAL", "OFFICE", "SHIPPING"]).optional(),
        street: zod
          .string()
          .min(createCustomerBodyAddressesItemStreetMin)
          .max(createCustomerBodyAddressesItemStreetMax),
        city: zod.string().min(createCustomerBodyAddressesItemCityMin).max(createCustomerBodyAddressesItemCityMax),
        state: zod.string().min(createCustomerBodyAddressesItemStateMin).max(createCustomerBodyAddressesItemStateMax),
        country: zod
          .string()
          .min(createCustomerBodyAddressesItemCountryMin)
          .max(createCustomerBodyAddressesItemCountryMax),
        pinCode: zod
          .string()
          .min(createCustomerBodyAddressesItemPinCodeMin)
          .max(createCustomerBodyAddressesItemPinCodeMax),
        version: zod.number().optional(),
        auditMetaData: zod
          .object({
            createdBy: zod.string().optional(),
            createdDate: zod.iso.datetime({}).optional(),
            lastModifiedBy: zod.string().optional(),
            lastModifiedDate: zod.iso.datetime({}).optional(),
          })
          .optional(),
      }),
    )
    .optional(),
  user: zod
    .object({
      id: zod.number().optional(),
      username: zod.string().min(1).max(createCustomerBodyUserUsernameMax),
      password: zod.string().min(createCustomerBodyUserPasswordMin).max(createCustomerBodyUserPasswordMax),
      email: zod.email().min(createCustomerBodyUserEmailMin).max(createCustomerBodyUserEmailMax),
      enabled: zod.boolean().optional(),
      roles: zod
        .array(
          zod.object({
            id: zod.number().optional(),
            role: zod.enum(["ROLE_CUSTOMER", "ROLE_USER", "ROLE_SELLER", "ROLE_ADMIN", "ROLE_MODERATOR"]).optional(),
          }),
        )
        .optional(),
      accountNonExpired: zod.boolean().optional(),
      credentialsNonExpired: zod.boolean().optional(),
      accountNonLocked: zod.boolean().optional(),
    })
    .optional(),
  version: zod.number().optional(),
  auditMetaData: zod
    .object({
      createdBy: zod.string().optional(),
      createdDate: zod.iso.datetime({}).optional(),
      lastModifiedBy: zod.string().optional(),
      lastModifiedDate: zod.iso.datetime({}).optional(),
    })
    .optional(),
  cart: zod
    .object({
      id: zod.number().optional(),
      cartItems: zod
        .array(
          zod.object({
            id: zod.number().optional(),
            product: zod
              .object({
                id: zod.number().optional(),
                name: zod
                  .string()
                  .min(createCustomerBodyCartCartItemsItemProductNameMin)
                  .max(createCustomerBodyCartCartItemsItemProductNameMax),
                description: zod
                  .string()
                  .min(createCustomerBodyCartCartItemsItemProductDescriptionMin)
                  .max(createCustomerBodyCartCartItemsItemProductDescriptionMax),
                price: zod.number().optional(),
                discountedPrice: zod.number().optional(),
                stock: zod.number().optional(),
                category: zod.object({
                  id: zod.number().optional(),
                  name: zod
                    .string()
                    .min(createCustomerBodyCartCartItemsItemProductCategoryNameMin)
                    .max(createCustomerBodyCartCartItemsItemProductCategoryNameMax),
                  version: zod.number().optional(),
                }),
                images: zod
                  .array(
                    zod.object({
                      id: zod.number().optional(),
                      fileName: zod.string().optional(),
                      contentType: zod.string().optional(),
                      downloadUrl: zod.string(),
                    }),
                  )
                  .optional(),
                version: zod.number().optional(),
                auditMetaData: zod
                  .object({
                    createdBy: zod.string().optional(),
                    createdDate: zod.iso.datetime({}).optional(),
                    lastModifiedBy: zod.string().optional(),
                    lastModifiedDate: zod.iso.datetime({}).optional(),
                  })
                  .optional(),
              })
              .optional(),
            quantity: zod.number().optional(),
            price: zod.number().optional(),
            discount: zod.number().optional(),
            auditMetaData: zod
              .object({
                createdBy: zod.string().optional(),
                createdDate: zod.iso.datetime({}).optional(),
                lastModifiedBy: zod.string().optional(),
                lastModifiedDate: zod.iso.datetime({}).optional(),
              })
              .optional(),
            discountedPrice: zod.number().optional(),
          }),
        )
        .optional(),
      totalPrice: zod.number().optional(),
      auditMetaData: zod
        .object({
          createdBy: zod.string().optional(),
          createdDate: zod.iso.datetime({}).optional(),
          lastModifiedBy: zod.string().optional(),
          lastModifiedDate: zod.iso.datetime({}).optional(),
        })
        .optional(),
    })
    .optional(),
  orders: zod
    .array(
      zod.object({
        id: zod.number().optional(),
        orderId: zod.uuid().optional(),
        orderStatus: zod.enum(["NEW", "PENDING", "SHIPPED", "COMPLETED", "CANCELLED"]).optional(),
        payment: zod
          .object({
            id: zod.number().optional(),
            paymentIdentifier: zod.uuid().optional(),
            paymentType: zod.enum(["CREDIT_CARD", "CASH", "PAYPAL", "BANK_TRANSFER"]).optional(),
            paymentStatus: zod.enum(["PENDING", "CREATED", "COMPLETED", "FAILED", "CANCELLED"]).optional(),
            paymentDetails: zod
              .object({
                cardHolderName: zod.string().optional(),
                cardType: zod.string().optional(),
                cardNumber: zod.string().optional(),
                expiryDate: zod.string().optional(),
                cvv: zod.string().optional(),
              })
              .optional(),
            amount: zod.number().optional(),
            paymentGatewayName: zod.string().optional(),
            paymentGatewayStatus: zod.string().optional(),
            paymentGatewayMessage: zod.string().optional(),
            paymentGatewayErrorDescription: zod.string().optional(),
            version: zod.number().optional(),
          })
          .optional(),
        orderItems: zod
          .array(
            zod.object({
              id: zod.number().optional(),
              product: zod
                .object({
                  id: zod.number().optional(),
                  name: zod
                    .string()
                    .min(createCustomerBodyOrdersItemOrderItemsItemProductNameMin)
                    .max(createCustomerBodyOrdersItemOrderItemsItemProductNameMax),
                  description: zod
                    .string()
                    .min(createCustomerBodyOrdersItemOrderItemsItemProductDescriptionMin)
                    .max(createCustomerBodyOrdersItemOrderItemsItemProductDescriptionMax),
                  price: zod.number().optional(),
                  discountedPrice: zod.number().optional(),
                  stock: zod.number().optional(),
                  category: zod.object({
                    id: zod.number().optional(),
                    name: zod
                      .string()
                      .min(createCustomerBodyOrdersItemOrderItemsItemProductCategoryNameMin)
                      .max(createCustomerBodyOrdersItemOrderItemsItemProductCategoryNameMax),
                    version: zod.number().optional(),
                  }),
                  images: zod
                    .array(
                      zod.object({
                        id: zod.number().optional(),
                        fileName: zod.string().optional(),
                        contentType: zod.string().optional(),
                        downloadUrl: zod.string(),
                      }),
                    )
                    .optional(),
                  version: zod.number().optional(),
                  auditMetaData: zod
                    .object({
                      createdBy: zod.string().optional(),
                      createdDate: zod.iso.datetime({}).optional(),
                      lastModifiedBy: zod.string().optional(),
                      lastModifiedDate: zod.iso.datetime({}).optional(),
                    })
                    .optional(),
                })
                .optional(),
              quantity: zod.number().optional(),
              orderItemTotalPrice: zod.number().optional(),
              version: zod.number().optional(),
              auditMetaData: zod
                .object({
                  createdBy: zod.string().optional(),
                  createdDate: zod.iso.datetime({}).optional(),
                  lastModifiedBy: zod.string().optional(),
                  lastModifiedDate: zod.iso.datetime({}).optional(),
                })
                .optional(),
            }),
          )
          .optional(),
        totalPrice: zod.number().optional(),
        shippingPrice: zod.number().optional(),
        version: zod.number().optional(),
      }),
    )
    .optional(),
});

export const saveCategoryBodyNameMin = 2;
export const saveCategoryBodyNameMax = 100;

export const SaveCategoryBody = zod.object({
  id: zod.number().optional(),
  name: zod.string().min(saveCategoryBodyNameMin).max(saveCategoryBodyNameMax),
  version: zod.number().optional(),
});

/**
 * Login with user details and get the Authorization JWT
 * @summary Login
 */
export const LoginBody = zod
  .object({
    username: zod.string(),
    password: zod.string(),
  })
  .describe("Wrapper for Username, Password");

/**
 * @summary Change a user's password
 */
export const changePasswordPathUsernameMax = 10;

export const ChangePasswordParams = zod.object({
  username: zod.string().min(1).max(changePasswordPathUsernameMax),
});

export const changePasswordQueryPasswordMin = 8;
export const changePasswordQueryPasswordMax = 100;

export const ChangePasswordQueryParams = zod.object({
  password: zod.string().min(changePasswordQueryPasswordMin).max(changePasswordQueryPasswordMax),
});

/**
 * Check if a username is taken
 * @summary Check if a username is taken
 */
export const isUsernameTakenPathUsernameMax = 10;

export const IsUsernameTakenParams = zod.object({
  username: zod.string().min(1).max(isUsernameTakenPathUsernameMax),
});

export const GetProductsByPageQueryParams = zod.object({
  name: zod.string(),
  page: zod.number(),
  size: zod.number(),
  sortDirection: zod.string(),
});

export const getAllProductsResponseNameMin = 3;
export const getAllProductsResponseNameMax = 500;

export const getAllProductsResponseDescriptionMin = 10;
export const getAllProductsResponseDescriptionMax = 600;

export const getAllProductsResponseCategoryNameMin = 2;
export const getAllProductsResponseCategoryNameMax = 100;

export const GetAllProductsResponseItem = zod.object({
  id: zod.number().optional(),
  name: zod.string().min(getAllProductsResponseNameMin).max(getAllProductsResponseNameMax),
  description: zod.string().min(getAllProductsResponseDescriptionMin).max(getAllProductsResponseDescriptionMax),
  price: zod.number().optional(),
  discountedPrice: zod.number().optional(),
  stock: zod.number().optional(),
  category: zod.object({
    id: zod.number().optional(),
    name: zod.string().min(getAllProductsResponseCategoryNameMin).max(getAllProductsResponseCategoryNameMax),
    version: zod.number().optional(),
  }),
  images: zod
    .array(
      zod.object({
        id: zod.number().optional(),
        fileName: zod.string().optional(),
        contentType: zod.string().optional(),
        downloadUrl: zod.string(),
      }),
    )
    .optional(),
  version: zod.number().optional(),
  auditMetaData: zod
    .object({
      createdBy: zod.string().optional(),
      createdDate: zod.iso.datetime({}).optional(),
      lastModifiedBy: zod.string().optional(),
      lastModifiedDate: zod.iso.datetime({}).optional(),
    })
    .optional(),
});
export const GetAllProductsResponse = zod.array(GetAllProductsResponseItem);

export const GetPaymentByIdParams = zod.object({
  paymentId: zod.uuid(),
});

export const GetOrderByIdParams = zod.object({
  orderId: zod.uuid(),
});

export const FindOrderByStatusParams = zod.object({
  orderStatus: zod.enum(["NEW", "PENDING", "SHIPPED", "COMPLETED", "CANCELLED"]),
});

export const GetOrderHistoryByIdParams = zod.object({
  id: zod.number(),
});

export const GetImageByNameParams = zod.object({
  imageName: zod.string(),
});

export const DownloadImageParams = zod.object({
  id: zod.number(),
});

export const GetCategoriesByPageQueryParams = zod.object({
  name: zod.string(),
  page: zod.number(),
  size: zod.number(),
  sortDirection: zod.string(),
});

/**
 * Delete a username
 */
export const deleteUserPathUsernameMax = 23;

export const DeleteUserParams = zod.object({
  username: zod.string().min(1).max(deleteUserPathUsernameMax),
});

export const DeleteImageByIdParams = zod.object({
  id: zod.number(),
});

/**
 * @summary Add product to cart
 */
export const DeleteCartQueryParams = zod.object({
  productId: zod.number(),
});
